name: bloc_clean_architecture_template
description: "A new Flutter project."


publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.10.7


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.9.1
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  go_router: ^17.1.0
  freezed_annotation: ^3.1.0
  injectable: ^2.7.1+4
  equatable: ^2.0.8
  shared_preferences: ^2.5.4
  logger: ^2.6.2
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.11.0
  injectable_generator: ^2.12.0
  freezed: ^3.2.5
  very_good_analysis: ^10.1.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - .env

  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_w200.ttf
          weight: 200
        - asset: assets/fonts/Inter_w300.ttf
          weight: 300
        - asset: assets/fonts/Inter_w400.ttf
          weight: 400
        - asset: assets/fonts/Inter_w500.ttf
          weight: 500
        - asset: assets/fonts/Inter_w600.ttf
          weight: 600
        - asset: assets/fonts/Inter_w700.ttf
          weight: 700
        - asset: assets/fonts/Inter_w800.ttf
          weight: 800
        - asset: assets/fonts/Inter_w900.ttf
          weight: 900
